### PR TITLE
V1.0.0 new shiny samson revision

### PR DESCRIPTION
**Pull request by michielrensen**
- Use v1660 of Samson
- Use newer version of other deps

### CODE REVIEW

**Comment by francoislapierremessier** [comment]
Was this tested anywhere? I'd much prefer testing this via an attribute change in an environment instead of of bumping the cookbook, as this will make patching of existing versions much harder.

**Comment by michielrensen** [comment]
@francoislapierremessier No this wasn't tested, how would I go about doing that? Deploying it to use1-dev maybe?

**Comment by francoislapierremessier** [comment]
Since it's an attribute, you can change the databag for policy_samson under use1dev to set the build  number without requiring a cookbook change.

**Comment by michielrensen** [comment]
Hmm alright, I will try that, thanks

**Comment by michielrensen** [comment]
@francoislapierremessier Tried going the attribute route, but it failed due to dependency on a newer ruby version (yes also tried setting that by attribute but it failed due to permission issues). 
So.. I guess we're stuck... Would really like to bump the version since we're so far behind, newer Samson would give us new features and more control/integrations.

**Pull request closed without merging**
